### ISSUE TITLE
KDE Plasma Wayland session using software rendering and is slow - va-api not working on nVidia

### ISSUE THREAD

**Issue by TraceyC77** [getsolus/packages#1742]
### Please confirm there isn't an existing open bug report

- [X] I have searched open bugs for this issue

### Summary

When logged into Plasma Wayland, rendering is slow. It is unusable with an external monitor. There is a warning in the system tray that software rendering is in use

### Steps to reproduce

Log into KDE Plasma with Wayland

### Expected result

System is as responsive as with X11

### Actual result

System is laggy, more so with an external monitor in use (laptop)

### Environment

- [X] Is system up to date?

### Repo

Unstable

### Desktop Environment

Plasma

### System details

Operating System: Solus 4.5
KDE Plasma Version: 5.27.10
KDE Frameworks Version: 5.115.0
Qt Version: 5.15.12
Kernel Version: 6.6.17-277.current (64-bit)
Graphics Platform: X11
Processors: 16 × 11th Gen Intel® Core™ i7-11800H @ 2.30GHz
Memory: 62.5 GiB of RAM
Graphics Processor: NVIDIA GeForce RTX 3060 Laptop GPU/PCIe/SSE2
Manufacturer: Dell Inc.
Product Name: XPS 17 9710

### Other comments

Plasma Wayland had been very usable up until around June 2023. After an update, it became laggy. I hadn't reported this before because I had been doing testing of VAAPI / Firefox with Reilly and thought that might have affected things. Even after removing the vaapi package, however, the performance is still slow.

As a workaround I tried setting `KWIN_DRM_USE_MODIFIERS=0` in `/etc/environment` as well as `KWIN_DRM_USE_MODIFIERS=1` but saw no change in performance.

- Removed nvidia vaapi driver package, no change
- Switched to nvidia-beta driver, no change
- xeglgears crashes [upstream mesa issue](https://gitlab.freedesktop.org/mesa/mesa/-/issues/10513)
-  May be related to [this closed issue 452219 in the KDE tracker](https://bugs.kde.org/show_bug.cgi?id=452219)

Possibly useful logs attached

[logs_wayland_compositing.txt](https://github.com/getsolus/packages/files/14413480/logs_wayland_compositing.txt)

**Comment by Conan-Kudo** [comment]
These issues sound like a variety of issues that were resolved as part of Plasma 6.0.

Another thing that could also help is turning on NVK in Mesa (with updating to Mesa 24) and setting `DRM_NOUVEAU_GSP_DEFAULT=y` in `linux-current` when you upgrade to 6.8. As long as you have the latest linux-firmware along for the ride, you can completely remove the need for the NVIDIA proprietary driver for NVIDIA Turing and newer GPUs.

**Comment by Conan-Kudo** [comment]
(Blame @EbonJaeger for me commenting there 😜 )

**Comment by TraceyC77** [comment]
Update: Problem persists after updating to Plasma 6 via regular updates with the unstable repo

**Comment by TraceyC77** [comment]
I found something that is probably related for nVidia GPU systems

I reinstalled  nvidia-vaapi-driver but VA-API is still not working

```bash
❯ vainfo
Trying display: wayland
libva info: VA-API version 1.22.0
libva info: User environment variable requested driver 'nvidia'
libva info: Trying to open /usr/lib64/dri/nvidia_drv_video.so
libva info: Found init function __vaDriverInit_1_0
libva error: /usr/lib64/dri/nvidia_drv_video.so init failed
libva info: va_openDriver() returns 1
vaInitialize failed with error code 1 (operation failed),exit
```

cc @ReillyBrogan

**Comment by Conan-Kudo** [comment]
Does your NVIDIA driver have kernel modesetting enabled? Without it, Plasma cannot use it.

Does your nvidia driver package have [this patch](http://pkgs.rpmfusion.org/cgit/nonfree/nvidia-kmod.git/tree/make_modeset_default.patch)?

**Comment by TraceyC77** [comment]
@ReillyBrogan, it doesn't look like nvidia-glx-driver has the patch mentioned above. Would you be up for including it?
I don't see anything about modesetting in the package.yml for the package, do we have this enabled?

**Comment by EbonJaeger** [comment]
It looks like the package installs a kernel cmdline conf file that includes `nvidia-drm.modeset=1`, is that it?

**Comment by joebonrichie** [comment]
https://github.com/getsolus/packages/blob/main/packages/n/nvidia-glx-driver/package.yml#L235
https://github.com/getsolus/packages/blob/main/packages/n/nvidia-glx-driver/files/cmdline-nvidia.conf

modeset is enabled by default for our nvidia driver, fbdev is not yet but we ship a patch to workaround it currently:

https://github.com/getsolus/packages/blob/main/packages/l/linux-current/files/patches/hardware/0001-drivers-firmware-skip-simpledrm-if-nvidia-drm.modese.patch

the `nvidia-vaapi-driver` package is unsupported. However, it should have no bearing on plasma using software rendering.
