### ISSUE TITLE
The keyboard backlight no longer works on Solus Budgie 4.5  on Macbook Pro 6.2 (mid 2010) after Update

### ISSUE THREAD

**Issue by grami-fr** [getsolus/packages#1861]
### Please confirm there isn't an existing open bug report

- [X] I have searched open bugs for this issue

### Summary

On Macbook Pro 6.2 (mid 2010) , the keyboard backlight works with Solus Budgie 4.4 , but not with Solus 4.5. 
No light..., and the F5 and F6 keys don't swith on/off the backlight. The "popup setting "for  the keyboard backlight  is show, but remains inactive when press F5-F6.  

### Steps to reproduce

1 Solus budgie 4.4 installed :  the keyboard Backlight work good
2 Update to 4.5 : the keyboard Backlight  don't work Anymore , 
3 On the  live session Solus Budgie 4.5 from on a USB Key, the backlight keyboard Works!

### Expected result

3 Reinstall Solus 4.5 on the SSD  from ISO Solus Budgie 4.5 : the keyboard Backlight work on the live Session on the USB Key.
4 But does not work anymore after the install on the ssd .

### Actual result

The keyboard backlight don't work with Solus Budgie 4.5. 
I managed to turn it on via  : "cd /sys/class/leds/smc::kbd_backlight/"  and : "cat max_brightness" in a terminal .
But the backlight stay always on, no adjustment possible.

### Environment

- [X] Is system up to date?

### Repo

Shannon (stable)

### Desktop Environment

Budgie

### System details

System:
  Host: macbook62 Kernel: 6.6.20-279.current arch: x86_64 bits: 64
  Desktop: Budgie v: 10.9.1 Distro: Solus 4.5 resilience
Machine:
  Type: Laptop System: Apple product: MacBookPro6,2 v: 1.0
    serial: <superuser required>
  Mobo: Apple model: Mac-F22586C8 v: MacBookPro6,2
    serial: <superuser required> UEFI: Apple v: MBP61.88Z.0057.B0F.1112091028
    date: 12/09/11
Battery:
  ID-1: BAT0 charge: 16.7 Wh (27.6%) condition: 60.4/75.2 Wh (80.3%)
    volts: 10.6 min: 10.9
CPU:
  Info: dual core Intel Core i5 M 540 [MT MCP] speed (MHz): avg: 1263
    min/max: 1197/2528
Graphics:
  Device-1: Intel Core Processor Integrated Graphics driver: i915 v: kernel
  Device-2: NVIDIA GT216M [GeForce GT 330M] driver: nouveau v: kernel
  Device-3: Apple Built-in iSight driver: uvcvideo type: USB
  Display: x11 server: X.Org v: 21.1.11 with: Xwayland v: 23.2.4 driver: X:
    loaded: modesetting,nouveau unloaded: fbdev,vesa dri: nouveau,crocus
    gpu: i915,nouveau resolution: 1: 1440x900~60Hz 2: 1440x900~60Hz
  API: OpenGL v: 3.3 compat-v: 2.1 vendor: mesa v: 24.0.2 renderer: NVA5
Network:
  Device-1: Broadcom NetXtreme BCM5764M Gigabit Ethernet PCIe driver: tg3
  Device-2: Broadcom BCM43224 802.11a/b/g/n driver: bcma-pci-bridge
Drives:
  Local Storage: total: 238.47 GiB used: 11.82 GiB (5.0%)
Info:
  Memory: total: 8 GiB available: 7.69 GiB used: 2.03 GiB (26.3%)
  Processes: 271 Uptime: 26m Shell: Bash inxi: 3.3.33
me@macbook62 ~ $

**Comment by UncleSlacky** [comment]
Same bug also present on the mid-2012 Macbook Pro (Macbook Pro 9,1).

**Comment by UncleSlacky** [comment]
Bug seems to have been resolved by the April 19th update (kernel 6.8?).

**Comment by grami-fr** [comment]
Hello, after the updates still not working... The keyboard backlighting still bugs (Macbook Pro 6.2 mid 2010).

**Comment by UncleSlacky** [comment]
Yes, after shutting down and rebooting today, the backlighting is now permanently on and the function key popup slider doesn't move from the zero/null position.

**Comment by tonyk94583** [comment]
I'm not sure what is different in my configuration - latest updated Solus Budgie - but keyboard backlight is working on my Macbook Pro 2012 (9,2) and Macbook Pro 2008? (4,1). One of the comments in the bug report has backlight issues with the same Macbook Pro 9,2, but mine is working.
It didn't work after the first restart after the new kernel, but after shutting down and turning on, the f5 and f6 work correctly to decrease/increase the keyboard backlight.

**Comment by UncleSlacky** [comment]
Weird, that's the exact opposite of my experience with Budgie on my MBP 9,2 (keys worked on the first boot into the kernel from the April 19th update, but not since). The kernel update that's just come out (6.8.7-287.current) hasn't changed the behaviour, either.

**Comment by tonyk94583** [comment]
My MBP 9.2 is an i7 with an Intel HD Graphics 4000.
Updated to the latest kernel (6.8.7-287) and keyboard backlight works fine and is adjustable with the f5/f6 keys.
Put the computer to sleep, and keyboard backlight is still working properly after waking up. Also worked properly after rebooting the computer.
After updating the kernel on my MPB 4,1 (to 6.8.7-287), the keyboard backlight adjustment via f5/f6 keys is not working. The MBP 4,1 has an old NVidia graphics card and uses the Nouveau drivers. The keyboard backlight was working fine on the previous kernel, so I will try rebooting a few more times and also boot to the previous kernel to see if it starts working.

**Comment by UncleSlacky** [comment]
OK, now this is really weird - after shutting down and rebooting, the F5/F6 keys are working now (MBP 9,2, mid-2012). So it seems that it's only the older models which still have problems?

**Comment by tonyk94583** [comment]
Yes, strange. After upgrading the kernel yesterday, the f5/f6 keys didn't work to adjust keyboard backlight on my 2008 MacbookPro (4,1), but worked fine on the 2012 MacbookPro (9,2). Tried rebooting, turning off, reset PRAM and SMC and no change. Saw your message this morning on github and tried again, and f5/f6 keys work properly for keyboard backlight adjustment on the 2008 MBP as well. Argh.
Running TLP on both Macbooks as well.

**Comment by ReillyBrogan** [comment]
There might be a kernel module that we're not building. Please do the following to generate a report of available kernel modules that I can compare with our kernel configuration:

- Download a recent version of Manjaro (https://manjaro.org/download/) (please use 23.1.4 based images). Doesn't matter which variant, though I'd probably go with GNOME or Plasma.
- Create a bootable USB or however you want to boot it on your hardware (I use Ventoy personally)
- Boot it
- Use all of the hardware that you can. Plug things into all of the different USB chips, use the speakers, etc. Different controllers, whatever you want to make sure works
- Run `lsmod | sort` and save the output to a file somewhere that persists between boots
- Boot back into Solus, specifically on the LTS kernel (kernel 6.6) or a slightly older version of linux-current on kernel 6.6
- Run `lsmod | sort` and save it somewhere as well.
- Upload both files to Pastebin/hastebin/whatever and give me the links. Make sure you label which one is Manjaro vs Solus

This uses Manjaro because they build every single available kernel module so it makes for a good comparison (we only build the ones that users likely need).

**Comment by UncleSlacky** [comment]
Thanks for your help, here are my files (Macbook Pro 9,2, mid-2012, Intel graphics):
https://pastebin.com/yZ5ar7iy (Manjaro)
https://pastebin.com/TZ54mUgF (Solus LTS 6.6)

This might be completely irrelevant, but I noticed that "mac_hid" is loaded by Manjaro but not Solus.

**Comment by ReillyBrogan** [comment]
I made a few config adjustments which will be in the next kernel builds for both linux-lts and linux-current. I don't know if they will help, but they might.

> This might be completely irrelevant, but I noticed that "mac_hid" is loaded by Manjaro but not Solus.

That's because on Solus we build `mac_hid` as a built-in, which means that it's always loaded and doesn't show up in the list.

**Comment by UncleSlacky** [comment]
Thanks for the quick response! I suspect only a minor adjustment is needed, as the function works sometimes (usually when I boot first thing in the morning, for some reason) and not at others, and in any case the popup always works even if the slider doesn't.

**Comment by UncleSlacky** [comment]
@ReillyBrogan in case it helps, I captured the lsmod output during a session where the keyboard backlight decided to work for some reason, this is with kernel 6.8.7-287.current: https://pastebin.com/V7VEUq6T

**Comment by UncleSlacky** [comment]
Still not working with latest kernel (6.8.8-288.current).

**Comment by UncleSlacky** [comment]
Still not working with latest kernel (6.8.9-289.current).

**Comment by UncleSlacky** [comment]
Working on about every fifth boot or so now with kernel 6.8.10-291.current.

**Comment by UncleSlacky** [comment]
Weirdly, it worked the first couple of times I booted with the new kernel (6.8.11-292.current) but not on the third.

**Comment by UncleSlacky** [comment]
With the last couple of kernels (currently on 6.8.12-293.current), per boot, it works about 50% of the time, possibly more often when plugged in than when running on battery. Maybe there's some kind of race condition involved?

**Comment by UncleSlacky** [comment]
For whatever reason, the last couple of kernels (cuurently on 6.9.12-297) the success rate per boot has deteriorated massively, to maybe 10% of the time at best.

**Comment by UncleSlacky** [comment]
Just an update, the backlight works maybe 50% of the time or more if you wait 10s or more to log in once the password entry field appears after boot. I've noticed in general that there is a delay in responding to keyboard input (a few seconds) after the password entry field appears after booting (longer if the previous shutdown wasn't clean) so maybe entering the password too soon is somehow preventing the keyboard backlight service(?) from terminating correctly? I guess because the machine is old (3rd gen i5) this may not be a significant issue on newer devices.

**Comment by UncleSlacky** [comment]
_Finally_ found a workaround - using Custom Shortcuts (Budgie Control Center -> Keyboard -> Keyboard Shortcuts -> View and Customize Shortcuts - > Custom Shortcuts) you can add functions for the F5 and F6 keys (KbdBrightnessDown and KbdBrightnessUp). I added the command `light -s sysfs/leds/smc::kbd_backlight -U 20` for Down and `light -s sysfs/leds/smc::kbd_backlight -A 20` for Up, which worked (after rebooting). You might have to change the permissions of the "light" command to be executable by all users, I can't remember if that was necessary or not.
